import { glob, readFile, writeFile } from 'node:fs/promises'

import { COMMON_ERROR_STATUS_MAP } from '@orpc/openapi'

const getStatusCode = (errorCode: string): number => {
  const prefix = errorCode.split('::')[0]
  return prefix in COMMON_ERROR_STATUS_MAP
    ? COMMON_ERROR_STATUS_MAP[prefix as keyof typeof COMMON_ERROR_STATUS_MAP]
    : 500
}

const sourceDir = new URL('../src/', import.meta.url)
const errorCodes = new Set<string>()

for await (const file of glob(['../src/**/*.ts', '../../../apps/api/src/**/*.ts'], {
  cwd: import.meta.dirname,
  exclude: ['error-status-map.ts']
})) {
  const source = await readFile(new URL(file, sourceDir), 'utf8')
  // ponytail: scan literal PREFIX::CODE strings; use a parser if comments or expressions need handling.
  for (const match of source.matchAll(/(['"`])([A-Z][A-Z0-9_]*::[A-Z][A-Z0-9_]*)\1/g)) {
    errorCodes.add(match[2])
  }
}

const entries = [...errorCodes].sort().map((code) => `  '${code}': ${getStatusCode(code)}`)

await writeFile(
  new URL('error-status-map.ts', sourceDir),
  [
    '// Generated by scripts/generate-error-status-map.ts. Do not edit manually.',
    "import { COMMON_ERROR_STATUS_MAP } from '@orpc/openapi'",
    '',
    'export type ErrorCode =',
    `  | ${[...errorCodes]
      .sort()
      .map((code) => `'${code}'`)
      .join('\n  | ')}`,
    '',
    'export const ErrorStatusMap = {',
    ['  ...COMMON_ERROR_STATUS_MAP', ...entries].join(',\n'),
    '}',
    ''
  ].join('\n')
)
