import { globSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { COMMON_ERROR_STATUS_MAP } from '@orpc/openapi'

const getStatusCode = (errorCode: string): number => {
  const prefix = errorCode.split('::')[0]
  return prefix in COMMON_ERROR_STATUS_MAP
    ? COMMON_ERROR_STATUS_MAP[prefix as keyof typeof COMMON_ERROR_STATUS_MAP]
    : 500
}

export const errorSourceDirs = [
  fileURLToPath(new URL('../src/', import.meta.url)),
  fileURLToPath(new URL('../../../apps/api/src/', import.meta.url))
]

export const generateErrorStatusMap = (): void => {
  const output = join(errorSourceDirs[0], 'error-status-map.gen.ts')
  const errorCodes = new Set<string>()

  for (const cwd of errorSourceDirs) {
    for (const file of globSync('**/*.ts', { cwd, exclude: ['**/*.gen.ts'] })) {
      const source = readFileSync(join(cwd, file), 'utf8')
      // ponytail: scan literal PREFIX::CODE strings; use a parser if comments or expressions need handling.
      for (const match of source.matchAll(/(['"`])([A-Z][A-Z0-9_]*::[A-Z][A-Z0-9_]*)\1/g)) {
        errorCodes.add(match[2])
      }
    }
  }

  const codes = [...errorCodes].sort()
  const entries = codes.map((code) => `  '${code}': ${getStatusCode(code)}`)
  const content = [
    '// Generated by scripts/generate-error-status-map.ts. Do not edit manually.',
    "import { COMMON_ERROR_STATUS_MAP } from '@orpc/openapi'",
    '',
    `export type ErrorCode = ${codes.length > 0 ? codes.map((code) => `'${code}'`).join(' | ') : 'never'}`,
    '',
    'export const ErrorStatusMap = {',
    ['  ...COMMON_ERROR_STATUS_MAP', ...entries].join(',\n'),
    '}',
    ''
  ].join('\n')

  try {
    if (readFileSync(output, 'utf8') === content) {
      return
    }
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
      throw error
    }
  }
  writeFileSync(output, content)
}

if (import.meta.main) {
  generateErrorStatusMap()
}
