// Generated by scripts/generate-error-status-map.ts. Do not edit manually.
import { COMMON_ERROR_STATUS_MAP } from '@orpc/openapi'

export type ErrorCode =
  | 'FORBIDDEN::REQUIRE_LOGIN'
  | 'FORBIDDEN::USER_NOT_FOUND'
  | 'NOT_IMPLEMENTED::FEATURE_NOT_IMPLEMENTED'

export const ErrorStatusMap = {
  ...COMMON_ERROR_STATUS_MAP,
  'FORBIDDEN::REQUIRE_LOGIN': 403,
  'FORBIDDEN::USER_NOT_FOUND': 403,
  'NOT_IMPLEMENTED::FEATURE_NOT_IMPLEMENTED': 501
}
