// Generated by scripts/generate-error-status-map.ts. Do not edit manually.
import { COMMON_ERROR_STATUS_MAP } from '@orpc/openapi'

export type ErrorCode =
  | 'FORBIDDEN::TASK_NOT_AUTHOR'
  | 'NOT_FOUND::TASK_NOT_FOUND'
  | 'NOT_IMPLEMENTED::FEATURE_NOT_IMPLEMENTED'
  | 'UNAUTHORIZED::NOT_SIGN_IN'

export const ErrorStatusMap = {
  ...COMMON_ERROR_STATUS_MAP,
  'FORBIDDEN::TASK_NOT_AUTHOR': 403,
  'NOT_FOUND::TASK_NOT_FOUND': 404,
  'NOT_IMPLEMENTED::FEATURE_NOT_IMPLEMENTED': 501,
  'UNAUTHORIZED::NOT_SIGN_IN': 401
}
