// Generated by scripts/generate-error-status-map.ts. Do not edit manually.
import { COMMON_ERROR_STATUS_MAP } from '@orpc/openapi'

export type ErrorCode = 'FORBIDDEN::REQUIRE_LOGIN' | 'FORBIDDEN::USER_NOT_FOUND'

export const ErrorStatusMap = {
  ...COMMON_ERROR_STATUS_MAP,
  'FORBIDDEN::REQUIRE_LOGIN': 403,
  'FORBIDDEN::USER_NOT_FOUND': 403
}
